import { useState } from 'react';
import { Alert, Pressable, Text, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Badge, Button, ChoiceChips, EmptyState, Field, ProgressBar, Screen, SectionTitle, Sheet, StateMessage, ui } from '@/components/ui';
import { ActionLink, EntityCard, IconTile, money } from '@/components/finance';
import { apiRequest } from '@/lib/api';
import type { Budget, Category } from '@/types/api';
import { theme } from '@/theme';

export default function BudgetsPage() {
  const now = new Date(); const client = useQueryClient(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Budget | null>(null); const [amount, setAmount] = useState(''); const [categoryId, setCategoryId] = useState('');
  const query = useQuery({ queryKey: ['budgets', now.getMonth(), now.getFullYear()], queryFn: () => apiRequest<Budget[]>(`/budgets?month=${now.getMonth() + 1}&year=${now.getFullYear()}`) });
  const categories = useQuery({ queryKey: ['categories'], queryFn: () => apiRequest<Category[]>('/categories') });
  const save = useMutation({ mutationFn: () => apiRequest(editing ? `/budgets/${editing.id}` : '/budgets', { method: editing ? 'PUT' : 'POST', body: JSON.stringify(editing ? { amount: Number(amount), categoryId: categoryId || null } : { amount: Number(amount), categoryId: categoryId || null, month: now.getMonth() + 1, year: now.getFullYear() }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ['budgets'] }); setOpen(false); } });
  const remove = useMutation({ mutationFn: (id: string) => apiRequest(`/budgets/${id}`, { method: 'DELETE' }), onSuccess: () => client.invalidateQueries({ queryKey: ['budgets'] }) });
  const start = (budget?: Budget) => { setEditing(budget || null); setAmount(String(budget?.amount || '')); setCategoryId(budget?.category?.id || ''); setOpen(true); };
  return <Screen title="Ngân sách" action={<Pressable onPress={() => start()}><MaterialCommunityIcons name="plus-circle" size={30} color={theme.colors.primary} /></Pressable>}><SectionTitle title={`Tháng ${now.getMonth() + 1}/${now.getFullYear()}`} caption="Kiểm soát chi tiêu theo từng danh mục" />{query.isLoading && <StateMessage loading message="Đang tải ngân sách…" />}{query.isError && <StateMessage message="Không thể tải ngân sách." />}{!query.isLoading && !query.data?.length && <EmptyState icon="piggy-bank-outline" title="Chưa đặt ngân sách" message="Tạo hạn mức để nhận cảnh báo khi chi tiêu đạt 80% và 100%." action={<Button label="Tạo ngân sách" onPress={() => start()} />} />}{query.data?.map((budget) => { const percent = Math.min(100, budget.percentage ?? ((budget.spent || 0) / Number(budget.amount)) * 100); const tone = percent >= 100 ? 'danger' : percent >= 80 ? 'warning' : 'primary'; return <EntityCard key={budget.id} icon={<IconTile name="piggy-bank-outline" color={tone === 'danger' ? theme.colors.danger : tone === 'warning' ? theme.colors.warning : theme.colors.primary} />} title={budget.category?.name || 'Tổng ngân sách'} subtitle={`${money(budget.spent || 0)} đã sử dụng`} badge={<Badge label={`${Math.round(percent)}%`} tone={tone === 'primary' ? 'info' : tone} />}><ProgressBar value={percent} tone={tone} /><View style={ui.between}><Text style={ui.muted}>Hạn mức</Text><Text style={ui.heading}>{money(budget.amount)}</Text></View><View style={ui.row}><View style={{ flex: 1 }}><ActionLink label="Chỉnh sửa" icon="pencil-outline" onPress={() => start(budget)} /></View><View style={{ flex: 1 }}><ActionLink danger label="Xóa" icon="trash-can-outline" onPress={() => Alert.alert('Xóa ngân sách?', undefined, [{ text: 'Hủy' }, { text: 'Xóa', style: 'destructive', onPress: () => remove.mutate(budget.id) }])} /></View></View></EntityCard>; })}<Sheet visible={open} title={editing ? 'Chỉnh sửa ngân sách' : 'Tạo ngân sách'} onClose={() => setOpen(false)}><Field label="Hạn mức" value={amount} onChangeText={setAmount} keyboardType="numeric" /><Text style={ui.muted}>Danh mục chi</Text><ChoiceChips value={categoryId} options={[{ label: 'Tổng chi tiêu', value: '' }, ...(categories.data || []).filter((item) => item.type === 'EXPENSE').map((item) => ({ label: item.name, value: item.id }))]} onChange={setCategoryId} /><Button label="Lưu ngân sách" loading={save.isPending} disabled={Number(amount) <= 0} onPress={() => save.mutate()} /></Sheet></Screen>;
}
