import { useState } from 'react';
import { Alert, Pressable, Text, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Badge, Button, ChoiceChips, EmptyState, Field, Screen, SectionTitle, Sheet, StateMessage, ui } from '@/components/ui';
import { ActionLink, EntityCard, IconTile, money } from '@/components/finance';
import { apiRequest } from '@/lib/api';
import type { Category, Wallet } from '@/types/api';
import { theme } from '@/theme';

interface Recurring { id: string; amount: string | number; type: 'INCOME' | 'EXPENSE'; frequency: string; note?: string; isActive: boolean; nextExecutionDate: string; wallet: Wallet; category: Category }

export default function RecurringPage() {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [type, setType] = useState('EXPENSE'); const [frequency, setFrequency] = useState('MONTHLY'); const [amount, setAmount] = useState(''); const [note, setNote] = useState(''); const [walletId, setWalletId] = useState(''); const [categoryId, setCategoryId] = useState('');
  const query = useQuery({ queryKey: ['recurring'], queryFn: () => apiRequest<Recurring[]>('/recurring') }); const wallets = useQuery({ queryKey: ['wallets'], queryFn: () => apiRequest<Wallet[]>('/wallets') }); const categories = useQuery({ queryKey: ['categories'], queryFn: () => apiRequest<Category[]>('/categories') });
  const create = useMutation({ mutationFn: () => apiRequest('/recurring', { method: 'POST', body: JSON.stringify({ walletId, categoryId, amount: Number(amount), type, frequency, note, startDate: new Date().toISOString() }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ['recurring'] }); setOpen(false); } });
  const toggle = useMutation({ mutationFn: (id: string) => apiRequest(`/recurring/${id}/toggle`, { method: 'PATCH' }), onSuccess: () => client.invalidateQueries({ queryKey: ['recurring'] }) }); const remove = useMutation({ mutationFn: (id: string) => apiRequest(`/recurring/${id}`, { method: 'DELETE' }), onSuccess: () => client.invalidateQueries({ queryKey: ['recurring'] }) });
  const filteredCategories = categories.data?.filter((item) => item.type === type) || [];
  return <Screen title="Định kỳ" action={<Pressable onPress={() => { setWalletId(wallets.data?.[0]?.id || ''); setCategoryId(''); setOpen(true); }}><MaterialCommunityIcons name="plus-circle" size={30} color={theme.colors.primary} /></Pressable>}><SectionTitle title="Giao dịch tự động" caption="Theo dõi hóa đơn, lương và khoản chi lặp lại" />{query.isLoading && <StateMessage loading message="Đang tải lịch định kỳ…" />}{!query.isLoading && !query.data?.length && <EmptyState icon="calendar-sync-outline" title="Chưa có giao dịch định kỳ" message="Tạo lịch để MoneyMate tự ghi nhận đúng hạn." />}{query.data?.map((item) => <EntityCard key={item.id} icon={<IconTile name="calendar-sync-outline" color={item.isActive ? theme.colors.primary : theme.colors.muted} />} title={item.note || item.category?.name || 'Giao dịch định kỳ'} subtitle={`${item.frequency} · Lần tới ${new Date(item.nextExecutionDate).toLocaleDateString('vi-VN')}`} value={money(item.amount)} badge={<Badge label={item.isActive ? 'Đang bật' : 'Tạm dừng'} tone={item.isActive ? 'success' : 'neutral'} />}><View style={ui.row}><View style={{ flex: 1 }}><ActionLink label={item.isActive ? 'Tạm dừng' : 'Bật lại'} icon={item.isActive ? 'pause-circle-outline' : 'play-circle-outline'} onPress={() => toggle.mutate(item.id)} /></View><View style={{ flex: 1 }}><ActionLink danger label="Xóa" icon="trash-can-outline" onPress={() => Alert.alert('Xóa lịch định kỳ?', undefined, [{ text: 'Hủy' }, { text: 'Xóa', style: 'destructive', onPress: () => remove.mutate(item.id) }])} /></View></View></EntityCard>)}<Sheet visible={open} title="Tạo giao dịch định kỳ" onClose={() => setOpen(false)}><Text style={ui.muted}>Loại giao dịch</Text><ChoiceChips value={type} options={[{ label: 'Khoản chi', value: 'EXPENSE' }, { label: 'Khoản thu', value: 'INCOME' }]} onChange={(value) => { setType(value); setCategoryId(''); }} /><Text style={ui.muted}>Chu kỳ</Text><ChoiceChips value={frequency} options={[{ label: 'Hàng ngày', value: 'DAILY' }, { label: 'Hàng tuần', value: 'WEEKLY' }, { label: 'Hàng tháng', value: 'MONTHLY' }, { label: 'Hàng năm', value: 'YEARLY' }]} onChange={setFrequency} /><Text style={ui.muted}>Ví</Text><ChoiceChips value={walletId} options={(wallets.data || []).map((item) => ({ label: item.name, value: item.id }))} onChange={setWalletId} /><Text style={ui.muted}>Danh mục</Text><ChoiceChips value={categoryId} options={filteredCategories.map((item) => ({ label: item.name, value: item.id }))} onChange={setCategoryId} /><Field label="Số tiền" value={amount} onChangeText={setAmount} keyboardType="numeric" /><Field label="Ghi chú" value={note} onChangeText={setNote} /><Button label="Tạo lịch" loading={create.isPending} disabled={!walletId || !categoryId || Number(amount) <= 0} onPress={() => create.mutate()} /></Sheet></Screen>;
}
