import type { ComponentProps } from 'react';
import {
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpDown,
  ArrowUpRight,
  Banknote,
  BarChart3,
  Bell,
  BellOff,
  Bot,
  Brain,
  BriefcaseBusiness,
  CalendarDays,
  CalendarX,
  Car,
  ChartPie,
  CheckCheck,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleMinus,
  CirclePause,
  CirclePlay,
  CirclePlus,
  CreditCard,
  Clock3,
  Download,
  Eye,
  EyeOff,
  Filter,
  Flashlight,
  Gamepad2,
  Gift,
  GraduationCap,
  Grid2X2,
  HeartPulse,
  Home,
  Images,
  Inbox,
  Keyboard,
  LayoutDashboard,
  Link,
  LockKeyhole,
  LogOut,
  Mail,
  MessageCircle,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Pencil,
  PiggyBank,
  Plus,
  ReceiptText,
  RefreshCw,
  ScanLine,
  Search,
  Send,
  Settings,
  Shapes,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Store,
  Sun,
  Tag,
  Tags,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  User,
  UserPlus,
  UserSearch,
  Users,
  Utensils,
  Wallet,
  WalletCards,
  X,
  type LucideIcon,
} from 'lucide-react-native';

/**
 * Semantic icon aliases used by the mobile UI. The components come from the
 * same Lucide family as the web frontend; legacy Material names remain as
 * aliases so API-provided category icon values keep working.
 */
const icons = {
  'account-group-outline': Users,
  'account-outline': User,
  'account-plus': UserPlus,
  'account-search-outline': UserSearch,
  'alert-circle-outline': CircleAlert,
  'alert-outline': CircleAlert,
  'arrow-bottom-left': ArrowDownLeft,
  'arrow-right': ArrowRight,
  'arrow-top-right': ArrowUpRight,
  'bank-outline': Wallet,
  'bell-outline': Bell,
  'bell-sleep-outline': BellOff,
  brain: Brain,
  briefcase: BriefcaseBusiness,
  'briefcase-outline': BriefcaseBusiness,
  'bullseye-arrow': Target,
  'calendar-alert': CalendarX,
  'calendar-blank-outline': CalendarDays,
  'calendar-month-outline': CalendarDays,
  'calendar-sync-outline': RefreshCw,
  car: Car,
  'car-outline': Car,
  'cash-multiple': Banknote,
  'cash-plus': Banknote,
  'chart-bar': BarChart3,
  'chart-box-outline': BarChart3,
  'chart-donut': ChartPie,
  'check-all': CheckCheck,
  'check-circle-outline': CircleCheck,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  close: X,
  'clock-outline': Clock3,
  'contactless-payment-circle-outline': Smartphone,
  creation: Sparkles,
  'credit-card-chip-outline': CreditCard,
  'dots-grid': Grid2X2,
  'dots-horizontal': MoreHorizontal,
  'dots-vertical': MoreVertical,
  'download-outline': Download,
  'email-outline': Mail,
  'eye-off-outline': EyeOff,
  'eye-outline': Eye,
  'filter-variant': Filter,
  'flash-outline': Flashlight,
  'gamepad-2': Gamepad2,
  'gamepad-variant-outline': Gamepad2,
  gift: Gift,
  'gift-outline': Gift,
  'graduation-cap': GraduationCap,
  'heart-pulse': HeartPulse,
  home: Home,
  'home-outline': Home,
  'image-multiple-outline': Images,
  'inbox-outline': Inbox,
  'keyboard-outline': Keyboard,
  'line-scan': ScanLine,
  'link-variant': Link,
  'lock-outline': LockKeyhole,
  'lock-check-outline': ShieldCheck,
  logout: LogOut,
  magnify: Search,
  'message-processing': MessageCircle,
  'more-horizontal': MoreHorizontal,
  'minus-circle-outline': CircleMinus,
  'pause-circle-outline': CirclePause,
  'pencil-outline': Pencil,
  'piggy-bank': PiggyBank,
  'piggy-bank-outline': PiggyBank,
  'play-circle-outline': CirclePlay,
  plus: Plus,
  'plus-circle-outline': CirclePlus,
  receipt: ReceiptText,
  'receipt-text': ReceiptText,
  'receipt-text-outline': ReceiptText,
  'robot-happy-outline': Bot,
  'scan-helper': ScanLine,
  'cog-outline': Settings,
  'school-outline': GraduationCap,
  send: Send,
  'shape-outline': Shapes,
  'shape-plus-outline': Shapes,
  'shield-account-outline': Shield,
  'shield-check-outline': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'shopping-outline': ShoppingBag,
  'silverware-fork-knife': Utensils,
  'storefront-outline': Store,
  sort: ArrowUpDown,
  'swap-horizontal': ArrowLeftRight,
  sync: RefreshCw,
  tag: Tag,
  'tag-multiple-outline': Tags,
  'tag-outline': Tag,
  target: Target,
  'trash-can-outline': Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'trophy-outline': Trophy,
  'tune-variant': Filter,
  utensils: Utensils,
  'view-dashboard': LayoutDashboard,
  'view-dashboard-outline': LayoutDashboard,
  'view-grid': Grid2X2,
  'view-grid-outline': Grid2X2,
  wallet: Wallet,
  'wallet-outline': Wallet,
  'wallet-plus-outline': WalletCards,
  'weather-night': Moon,
  'white-balance-sunny': Sun,
} satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof icons;
type LucideProps = ComponentProps<LucideIcon>;

export function AppIcon({
  name,
  strokeWidth = 2.1,
  ...props
}: Omit<LucideProps, 'name'> & { name: AppIconName | string }) {
  const Icon = icons[name as AppIconName] ?? Tag;
  return <Icon aria-hidden strokeWidth={strokeWidth} {...props} />;
}
