import type { CSSProperties } from 'react';
import { webTheme } from '@moneymate/design-tokens';

/** SVG and Recharts props use the same CSS variables generated by Tailwind. */
export const chartTheme = {
  ...webTheme.chart,
  income: 'rgb(var(--chart-income))',
  expense: 'rgb(var(--chart-expense))',
  savings: 'rgb(var(--chart-savings))',
  warning: 'rgb(var(--chart-warning))',
  grid: 'rgb(var(--ui-grid))',
  muted: 'rgb(var(--ui-muted))',
  palette: ['blue', 'purple', 'income', 'warning', 'expense', 'cyan', 'orange', 'violet'].map((name) => `rgb(var(--chart-${name}))`),
  tooltip: {
    background: 'rgb(var(--ui-surface))',
    border: '1px solid rgb(var(--ui-border))',
    borderRadius: webTheme.borderRadius.control,
    color: 'rgb(var(--ui-text))',
    fontSize: webTheme.chart.tickSize,
    fontWeight: 600,
  } satisfies CSSProperties,
};
